### ISSUE TITLE
as a member i can log out 

### ISSUE THREAD

**Issue by Donia1** [yousraHazem/topsoft-13#159]
success: 
you press the button it redirects to the home page and everything looks as if he is a guest 
failure:
have to check that nothing is open and everything he did is saved 
TASKS:
revers log in 
documentation of methods
story sequence diagram

@mayBadr @yasmin-eltahan @mariam-ismail @samaakram

**Comment by yasmin-eltahan** [comment]
I have checked the UML and verified it

**Comment by samaakram** [comment]
@Donia1 
Code Review:
in user controller: wrong indentation with def show. so u should unindent def show line
in admin helper, session helper, user helper: indentation problems with def's ends. make sure they have same indentation as their opening defs
in views/admin/index.html.erb: indentation problem. line 9, 24, 26 should have same indentation
and you have to closing divs without their opening so should be removed from line 16 and 17

**Comment by samaakram** [comment]
@Donia1 
Doc Review:
in admin controller, wrong documentation/description of def new, this method does not redirect to any other page as stated and also doesnt take any params
in app controller change the descriptions to something like it takes first id and finds it in users to be more clear

**Comment by Donia1** [comment]
@yasmin-eltahan  i have updated the uml for logout

**Comment by yasmin-eltahan** [comment]
Uml verified

**Comment by Donia1** [comment]
@samaakram  please check my documentation

**Comment by samaakram** [comment]
@Donia1
documentation review:
the last version of your branches i could find here were the ones last updated 4 days ago. they are still missing the "it returns" statement

**Comment by samaakram** [comment]
@Donia1 
documentation review:
in SessionsController:
you can delete the def new since you dint use it and put the documentation just for def create and def destroy you misspelled returns
in UsersController:
def show wrong doc; it actually takes/ARGS the user.id and returns the groupUser record, where its user.id = current_user.id
def create it returns the new user record/session record so instead of saying all info about ... say record
in SessionsHelper
def log_in(user): either return user or user.id and take another look at the misspelled words 
and fill in the documentation for the rest of you methods
and while fixing the mistakes make sure you also wrote the ARGS/it takes statement

PS: ill also write you my comments on your code (code review) so you can fix them both at one time

**Comment by samaakram** [comment]
Code Review:
in ApplicationController & UsersController & UsersHelper & app / views / admin / show.html.erb & app / views / user/_getMyGroups.html.erb , show.html.erb
wrong indentation

**Comment by Donia1** [comment]
@samaakram i fixed the code

**Comment by samaakram** [comment]
@Donia1 code verified

**Comment by samaakram** [comment]
@Donia1 doc verified

**Comment by samaakram** [comment]
@Donia1 
doc review
on the master you pushed your old branch with the old mistakes
so please fix them and also in sessionController i cant find your ID anymore!! and def show it doesnt take the session ID it takes/ARGS :user_id

**Comment by mariam-ismail** [comment]
@Donia1  please recheck your tests as you have 4 failures in users model
