### ISSUE TITLE
As an admin I can create a project

### ISSUE THREAD

**Issue by nayera-muhammad** [yousraHazem/topsoft-13#177]
branch name: c2_nayera_as_a_creator_edit_project
product backlog number:  32
success:
view a list of the tasks available for a certain project
failure:
no task selected

Tasks:
1. code @Riham-Gamal 
2. Documentation @salmaelruby 
3. UML  @salmaelruby 
4. test @mariam-ismail 
5. Bootstrap

**Comment by salmaelruby** [comment]
documentation review @nayera-muhammad 
 in project controller 
- in def create project "this method takes its' input from the params" u should specify which params ? 
- in def edit project "@project_count = Project.count"  you didnt desribe what does this do 
- in def update project this sentence needs to be paraphrased its not clear ==> " takes the updated attributes in order to change them"

**Comment by salmaelruby** [comment]
UML review : please add the models and views needed and the correct returned output :)

**Comment by nayera-muhammad** [comment]
@salmaelruby please review me and i added my uml files

**Comment by Riham-Gamal** [comment]
scenario and code are verified

**Comment by salmaelruby** [comment]
uml verified

**Comment by nayera-muhammad** [comment]
@salmaelruby  please review my documentation

**Comment by Riham-Gamal** [comment]
scenario is verified
