### ISSUE TITLE
as a member i can view my groups 

### ISSUE THREAD

**Issue by Donia1** [yousraHazem/topsoft-13#195]
@mariam-ismail @mayBadr @samaakram @yasmin-eltahan

**Comment by yasmin-eltahan** [comment]
I have checked the UML and verified it

**Comment by Donia1** [comment]
@yasmin-eltahan undated the umls

**Comment by yasmin-eltahan** [comment]
there is something wrong with the format of this UML please check it out

**Comment by Donia1** [comment]
@samaakram sama please check my documentation

**Comment by Donia1** [comment]
@yasmin-eltahan check my uml please

**Comment by samaakram** [comment]
@Donia1
documentation review:
the last version of your branches i could find here were the ones last updated 4 days ago. they are still missing the "it returns" statement

**Comment by samaakram** [comment]
@Donia1 
documentation review:
in SessionsController:
you can delete the def new since you dint use it and put the documentation just for def create and def destroy you misspelled returns
in UsersController:
def show wrong doc; it actually takes/ARGS the user.id and returns the groupUser record, where its user.id = current_user.id
def create it returns the new user record/session record so instead of saying all info about ... say record
in SessionsHelper
def log_in(user): either return user or user.id and take another look at the misspelled words 
and fill in the documentation for the rest of you methods
and while fixing the mistakes make sure you also wrote the ARGS/it takes statement

PS: ill also write you my comments on your code (code review) so you can fix them both at one time

**Comment by samaakram** [comment]
Code Review:
in ApplicationController & UsersController & UsersHelper & app / views / admin / show.html.erb & app / views / user/_getMyGroups.html.erb , show.html.erb
wrong indentation

**Comment by samaakram** [comment]
@Donia1 code verified
@Donia1 doc verified

**Comment by yasmin-eltahan** [comment]
@Donia1  same problem

**Comment by Donia1** [comment]
@yasmin-eltahan
